config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: "pages#home"

  resources :hikes do
    member do
      post "confirm", to: 'hikes#confirm'
      post "unconfirm", to: 'hikes#unconfirm'
    end
    resources :markers, only: [:index, :new, :create, :destroy], path: 'routes', as: :routes
    resources :requests, only: [:create]
    resources :chatrooms, only: :index do
      resources :messages, only: :create
    end
  end
  resources :requests, only: [:index], path: 'my_hikes' do
    post "/accept", to: 'requests#accept'
    post "/reject", to: 'requests#reject'
  end
  resources :chatrooms, only: :index do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-icons-flexbox">
    <a href="/hikes/new" class="footer-add-button"><i class="fa-solid fa-circle-plus footer-plus-icon"></i></a>
    <div class="left-icons">
      <a href="/" class="<%= params[:action] == "home" ? "footer-icon-active" : "footer-icon" %>"><i class="fa-solid fa-house footer-main-icon"></i></a>
      <a href="/hikes" class="<%= params[:controller] == "hikes" && params[:action] == "index" ? "footer-icon-active" : "footer-icon" %>"><i class="fa-solid fa-location-dot footer-main-icon"></i></a>
    </div>
    
    
    <div class="right-icons">
      <a href="/my_hikes" class="<%= params[:controller] == "requests" && params[:action] == "index" ? "footer-icon-active" : "footer-icon" %>"><i class="fa-solid fa-envelope footer-main-icon"></i></a>
      <% if user_signed_in? %>
        <%= link_to user_path(current_user), class:  params[:action] == "show" ? "footer-icon-active" : "footer-icon"  do %> <i class="fa-solid fa-user footer-main-icon"></i> <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "footer-icon" do %> <i class="fa-solid fa-user footer-main-icon"></i> <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_map_card_index.html.erb
<div class="map-card-index">
  <div class="map-card-img" style="background-image: url('<%= cl_image_path @hike.photo.key %>')"></div>
  <div class="map-card-bottom-section-flex">
    <div class="map-card-info">
      <p class="map-card-name"><%= @hike.hike_name.truncate(14, separator: ',') %></p>
      <p class="map-card-text">Difficulty: <%= @hike.difficulty %></p>
      <p class="map-card-text">Distance: <%= @hike.distance %></p>
    </div>
    <div class= "map-card-btn">
      <%= link_to "Go to Hike", hike_path(hike) %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-shoe-prints"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-user"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "logoutlink-navbar" unless user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, class: "logoutlink-navbar", data: { turbo_method: :delete} if user_signed_in? %>
          </li>
      </ul>
    </div>
  </div>
</div>