config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: "pages#home"

  resources :hikes do
    member do
      post "confirm", to: 'hikes#confirm'
      post "unconfirm", to: 'hikes#unconfirm'
    end
    resources :markers, only: [:index, :new, :create, :destroy], path: 'routes', as: :routes
    resources :requests, only: [:create]
    resources :chatrooms, only: :index do
      resources :messages, only: :create
    end
  end
  resources :requests, only: [:index], path: 'my_hikes' do
    post "/accept", to: 'requests#accept'
    post "/reject", to: 'requests#reject'
  end
  resources :chatrooms, only: :index do
    resources :messages, only: :create
  end
end

app/models/hike.rb
class Hike < ApplicationRecord
  has_many :requests, dependent: :destroy
  has_many :markers, dependent: :destroy
  has_many :users, through: :requests
  belongs_to :user
  has_one_attached :photo

  validates_presence_of :hike_name, :hike_description, :max_people

  geocoded_by :starting_point
  after_validation :geocode, if: :will_save_change_to_starting_point?

  has_one :chatroom, dependent: :destroy
  after_create :add_chatroom

  def in_past?
    hike_date < Date.today if hike_date
  end

  def in_future?
    hike_date >= Date.today if hike_date
  end

  def complete_hike!
    update(hike_completed: true)
  end

  def self.complete_hikes_if_necessary!
    all.each do |hike|
      if hike.in_past?
        hike.complete_hike!
      end
    end
  end

  private

  def add_chatroom
    Chatroom.create!(name: self.hike_name, hike: self)
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :set_hike, only: %i[show edit destroy update confirm unconfirm]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @hikes = Hike.all
    @upcoming_hikes = Hike.where("hike_date >= ?", Date.today).or(Hike.where(hike_date: nil))

    @markers = @upcoming_hikes.geocoded.map do |hike|
      {
        lat: hike.latitude,
        lng: hike.longitude,
        info_window_html: render_to_string(partial: "hike_map_window", locals: {hike: hike}),
        marker_html: render_to_string(partial: "hiker_marker", locals: {hike: hike}),
      }
    end
  end

  def new
    @hike = Hike.new
  end

  def create
    @hike = Hike.new(hike_params)
    @hike.user = current_user
    if @hike.save!
      redirect_to hike_path(@hike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @request = Request.where(hike: @hike, user: current_user)
    @accepted_requests = Request.where(hike: @hike, request_accepted: true)

    if @hike.in_past?
      @hike.complete_hike!
    end

    @accepted_hiker = @accepted_requests.each do |request|
      User.where(id: request.user_id).first
    end

    @markers = @hike.markers.order(:order)
    @marker_coordinates = @markers.map { |marker| [marker.longitude, marker.latitude] }
    if @markers.count != 0
      @marker_coordinates = @markers.map { |marker| [marker.longitude, marker.latitude] }
      @marker_initial_coordinates = {
        lng: @markers[0].longitude,
        lat: @markers[0].latitude,
        marker_html: render_to_string(partial: "start_marker")
      }
      @marker_finish_coordinates = {
        lng: @markers[-1].longitude,
        lat: @markers[-1].latitude,
        marker_html: render_to_string(partial: "finish_marker")
      }
    end
    @start_coordinates = [@hike.longitude, @hike.latitude]
  end

  def edit; end

  def update
    if @hike.update(hike_params)
      redirect_to hike_path(@hike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @hike.destroy
    redirect_to hikes_path, status: :see_other
  end

  def confirm
    @hike.hike_confirmed = true
    if @hike.save
      redirect_to hike_path
    else
      render 'hikes/show', status: :unprocessable_entity
    end
  end

  def unconfirm
    @hike.hike_confirmed = false
    if @hike.save
      redirect_to hike_path
    else
      render 'hikes/show', status: :unprocessable_entity
    end
  end

  def route
    @hike = Hike.find(params[:hike_id])
    @markers = @hike.markers.order(:order)
  end

  private

  def set_hike
    @hike = Hike.find(params[:id])
  end

  def hike_params
    params.require(:hike).permit(
      :hike_name, :hike_description, :difficulty, :distance, :max_people,
      :hike_date, :photo, :starting_point, :hike_confirmed, :hike_completed
    )
  end
end

app/views/hikes/_finish_marker.html.erb
<%= image_tag "finish.png", height: 30, width: 30, alt: "Logo", class: "green-pin" %>

app/views/hikes/_form.html.erb
<%# <div class="login-form-container"> %>
<%# <div class="form-content"> %>
  <%= simple_form_for @hike do |f| %>
    <%= f.input :hike_name, label: "Hike name:", placeholder: 'Cairngorms National Park Hike'%>
    <%= f.input :hike_description, label: "Description:", placeholder: 'A lovely hike with stops for lunch' %>
    <%= f.input :difficulty, label: "Difficulty:", collection: ["Easy 🟢", "Medium 🟡", "Hard 🔴"] %>
    <%= f.input :max_people, label: "Max. number of people:", placeholder: '5' %>
    <%= f.input :starting_point, as: :hidden, label: "Starting location:",
        input_html: {data: {address_autocomplete_target: "address"}},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
        class: "mapbox-search-form"
      %>
    <%= f.input :hike_date, as: :string,
                wrapper_html: { class: "mb-4" },
                label_html: { class: "form-label" },
                input_html: { data: { controller: "flatpickr" } } %>    <%= f.input :photo, as: :file %>
    <div>
      <%= f.button :submit, class: "btn-yellow", value: "Add Hike" %>
    </div>
  <%end%>

<%# </div> %>

</div>

app/views/hikes/_hike_map_window.html.erb
<div class="map-card-index">
  <% if hike.photo.attached? %>
      <div class="map-card-img" style="background-image: url('<%= cl_image_path hike.photo.key %>')"></div>
  <% else %>
      <div class="map-card-img" style="background-image: url('https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')"></div>
  <% end %>
  <div class="map-card-bottom-section-flex">
    <div class="map-card-info">
      <h3 class="map-card-name"><%= hike.hike_name.truncate(14, separator: ',')%></h3>
      <p class="map-card-text"><strong> Difficulty:</strong> <%= hike.difficulty %> </p>
      <p class="map-card-text"><strong>Distance:</strong> <%= hike.distance %></p>
    </div>
    <div class= "map-card-btn">
      <%= link_to "Go to Hike", hike_path(hike) %>
    </div>
  </div>
</div>

app/views/hikes/_hiker_marker.html.erb
<div class="fs-1">
  <i class="fa-solid fa-person-hiking man"></i>
</div>

app/views/hikes/_start_marker.html.erb
<%= image_tag "start.png", height: 30, width: 30, alt: "Logo", class: "green-pin" %>

app/views/hikes/edit.html.erb
<div class="edit-form">
  <h2>Edit your new hike</h2>
  <%= render 'hikes/form' %>
</div>

app/views/hikes/index.html.erb
<% content_for :meta_title, "All Hikes" %>
<div style="width: 100%; height: 900px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/hikes/new.html.erb
<% content_for :meta_title, "Add a New Hike" %>

<div class="login-form-container">
    <div class="main-title">
      <h1>Add a new Hike</h1>
    </div>
    <div class="form-content-plus">
      <%= render 'hikes/form'%>
      <p>* Required field</p>
    </div>
</div>

app/views/hikes/show.html.erb
<% content_for :meta_title, "#{@hike.hike_name}" %>
<% content_for :meta_description, @hike.hike_description %>
<% content_for :meta_image, cl_image_path(@hike.photo.key) if @hike.photo.attached? %>

<div class="page-container-flex">

  <!-- THIS IS THE PART OF THE SHOW PAGE EVERYONE SEES -->

  <div class="hike-img-title">
    <% if @hike.photo.attached? %>
    <div class="hike-page-info-img" style="background-image: url('<%= cl_image_path @hike.photo.key %>')">
    <% else %>
    <div class="hike-page-info-img" style="background-image: url('https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')">
    <% end %>
      <div class="back-edit-delete-flex">
        <%= link_to hikes_path do %>
          <div class="back-icon-show">
            <i class="fa-solid fa-arrow-left"> </i>
            <i class="fa-solid fa-map-location-dot"></i>
          </div>
        <% end %>
        <% if @hike.user == current_user %>
        <div class="edit-delete-icons">
          <%= link_to edit_hike_path do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to hike_path(@hike), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="hike-title-avatars-flex">
      <h1><%= @hike.hike_name%></h1>
      <%= link_to user_path(@hike.user) do %>
        <p><% if @hike.user.photo.attached? %>
          <%= cl_image_tag @hike.user.photo.key, class: "avatar" %>
        <% end %>
        <%= @hike.user.first_name %> <%= @hike.user.last_name %></p>
      <% end %>
    </div>
  </div>

  <br>

  <div class="hike-page-info-card">
    <div class="hike-route-container">
      <h2>Route</h2>
      <div class="hike-icons-map">
        <div id="map"
          data-controller="hike-map"
          data-hike-map-marker-initial-coordinates-value="<%= @marker_initial_coordinates.to_json %>"
          data-hike-map-marker-finish-coordinates-value="<%= @marker_finish_coordinates.to_json %>"
          data-hike-map-marker-coordinates-value="<%= @marker_coordinates.to_json %>"
          data-hike-map-start-coordinates-value="<%= @start_coordinates.to_json %>"
          data-hike-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
          style="height: 200px;">
        </div>
        <div class="map-icons-flex">
          <% if @hike.user == current_user %>
            <div class="map-icons-box" id="set-route">
              <% if @hike.markers.exists? %>
                <%= link_to ' + Set new route', new_hike_route_path(@hike) %>
              <% else %>
                <%= link_to '+ Set route', new_hike_route_path(@hike) %>
              <% end %>
          </div>
          <% else %>
            <p></p>
          <% end %>
          <div class="map-icons-box" id="maximise">
            <%= link_to hike_routes_path(@hike) do %>
              <i class="fa-solid fa-up-right-and-down-left-from-center"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="hike-page-info-text">
      <div class="hike-page-details-flex">
        <div class="hike-page-details-1">
          <p> <i class="fa-solid fa-location-dot"></i> &nbsp; <%= @hike.starting_point.split(",").first %></p>
          <p> <i class="fa-solid fa-route"></i> &nbsp; <%= @hike.distance.nil? ? "TBC" : @hike.distance %> (km) </p>
          <p> <i class="fa-solid fa-gauge-simple-high"></i> &nbsp; <%= @hike.difficulty %></p>
        </div>
        <div class="hike-page-details-2">
          <p> <i class="fa-solid fa-person-hiking"></i> &nbsp; <%= @accepted_requests.count + 1 %> / <%= @hike.max_people %> Hikers </p>
          <% if @hike.hike_date.blank? %>
            <p> <i class="fa-regular fa-calendar"></i> &nbsp; TBC </p>
          <% else %>
            <p> <i class="fa-regular fa-calendar"></i> &nbsp; <%= @hike.hike_date.strftime("%b %d, %Y") %></p>
          <% end %>

          <% if @hike.hike_confirmed %>
            <p> <i class="fa-regular fa-calendar-check"></i> &nbsp; Confirmed ✅</p>
          <% else %>
            <p> <i class="fa-regular fa-calendar-xmark"></i> &nbsp; Not confirmed</p>
          <% end %>
        </div>
      </div>


      <div class="hike-page-description">
        <p> <%= @hike.hike_description %> </p>
      </div>
    </div>


    <!-- THIS IS THE SHOW PAGE WHEN YOU HAVEN'T REQUESTED TO JOIN -->
  <% if @request.empty? && @hike.user != current_user %>
    <% if @accepted_requests.count + 1 == @hike.max_people %>
      <div class="pending-button">
        <button class= "btn-yellow pending-request-button"> Hike full, sorry!</button>
      </div>

    <% elsif @hike.hike_completed %>
      <div class="pending-button">
        <button class= "btn-yellow pending-request-button"> Hike happened!</button>
      </div>

    <% else %>
      <div class="request-button">
        <%= button_to 'Join Hike', hike_requests_path(@hike), method: :post, class: "btn-yellow"%>
      </div>
    <% end %>

        <!-- THIS IS THE SHOW PAGE WHEN YOU'VE BEEN ACCEPTED -->
  <% elsif @hike.user == current_user || @request.last.request_pending == false && @request.last.request_accepted == true %>

    <!-- CODE FOR WHAT THE ACCEPTED HIKER SEES -->
    <div class="confirm-hike-button-flex">
      <% if @hike.hike_confirmed == false && current_user != @hike.user %>
        <hr>
        <p><em> This Hike hasn't been confirmed by the owner yet. Chat to your fellow Hikers to finalise a route, date, and time! </em></p>
      <% elsif @hike.hike_confirmed == true && current_user != @hike.user %>
        <hr>
        <p><em>This Hike is now confirmed! Get your backpack ready!</em></p>
      <% end %>
    </div>

    <!-- CODE FOR WHAT THE OWNER SEES -->
    <% if current_user == @hike.user %>
      <div class="confirm-hike-button-flex">
        <% if @hike.hike_confirmed %>
          <hr>
          <p><em>This Hike is now confirmed! Get your backpack ready!</em></p>
          <%= link_to 'Unconfirm Hike', unconfirm_hike_path(@hike), class: "unconfirm-hike-button" %>
        <% else %>
          <% if @hike.hike_date.blank? %>
            <hr>
            <p><em>This Hike isn't confirmed yet! Once you've decided a route, date, and time with your fellow Hikers, confirm the Hike so everyone knows it's happening.</em></p>
          <button class= "btn-yellow pending-request-button">Please Set Date</button>
          <% else %>
            <hr>
            <p><em>This Hike isn't confirmed yet! Once you've decided a route, date, and time with your fellow Hikers, confirm the Hike so everyone knows it's happening.</em></p>
            <%= button_to 'Confirm Hike', confirm_hike_path(@hike), class: "btn-yellow hike-confirm-button" %>
          <% end %>
        <% end %>
      </div>
      <% end %>
  </div>
  <br>
      <div class="hike-page-hikers">
        <h2>Hikers</h2>

        <div class="hikers-joined-details-flex">
          <% if @hike.user.photo.attached? %>
            <%= cl_image_tag @hike.user.photo.key, class: "avatar-large" %>
          <% end %>

          <%= link_to user_path(@hike.user), class: "request-user-info-flex" do %>
            <p><%= @hike.user.first_name %> <%= @hike.user.last_name %> (Hike creator) </p>
          <% end %>
        </div>

        <% if @accepted_requests.any? %>
          <% @accepted_requests.each do |request| %>
            <div class="hikers-joined-details-flex">
              <% accepted_hiker = User.where(id: request.user_id).first %>
                <% if accepted_hiker.photo.attached? %>
                  <%= cl_image_tag accepted_hiker.photo.key, class: "avatar-large" %>
                <% end %>
                <%= link_to user_path(request.user), class: "request-user-info-flex" do %>
                  <p><%= accepted_hiker.first_name %> <%= accepted_hiker.last_name %> </p>
                <% end %>
            </div>
            <% end %>
        <% end %>
        <% if @hike.max_people == @accepted_hiker.count + 1 %>
          <p> This Hike is full. </p>
        <% else %>
          <p> There's space for <%= (@hike.max_people) - (@accepted_hiker.count + 1)%> more in this Hike!</p>
        <% end %>

          <div class="hike-chat-button-flex">
            <hr>
            <p><em>Chat to your fellow Hikers to coordinate your Hike!</em></p>
            <%= link_to 'Hike Chat', hike_chatrooms_path(@hike), class: "btn-yellow hike-chat-button" %>
          <div>
      </div>

                  <!-- THIS IS THE SHOW PAGE WHEN YOU'VE REQUESTED AND ARE PENDING -->
    <% elsif  @request.last.request_pending == true && @request.last.request_accepted == false %>
      <div class="pending-button">
        <button class= "btn-yellow pending-request-button">Pending</button>
      </div>


                  <!-- THIS IS THE SHOW PAGE WHEN YOU'VE BEEN REJECTED -->

    <% elsif @request.last.request_pending == false && @request.last.request_accepted == false %>
      <p>Sorry, you have not been accepted into this Hike</p>
    <% end %>
  </div>
</div>
</div>