config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: "pages#home"

  resources :hikes do
    member do
      post "confirm", to: 'hikes#confirm'
      post "unconfirm", to: 'hikes#unconfirm'
    end
    resources :markers, only: [:index, :new, :create, :destroy], path: 'routes', as: :routes
    resources :requests, only: [:create]
    resources :chatrooms, only: :index do
      resources :messages, only: :create
    end
  end
  resources :requests, only: [:index], path: 'my_hikes' do
    post "/accept", to: 'requests#accept'
    post "/reject", to: 'requests#reject'
  end
  resources :chatrooms, only: :index do
    resources :messages, only: :create
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :hike
  belongs_to :user

  scope :accepted, -> { where(request_accepted: true) }
  scope :pending, -> { where(request_pending:true) }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_hike, only: [:create]

  def index
    @user_id = current_user.id
    @requests = Request.where(user_id: @user_id)
    @pending_requests = Request.where(request_pending: true)
    @hikes = Hike.where(user_id: @user_id)
    @accepted_requests = Request.accepted
  end

  def create
    @request = Request.new
    @request.hike = @hike
    @request.user = current_user
    if @request.save
      redirect_to hike_path(@hike)
    else
      render 'requests/new', status: :unprocessable_entity
    end
  end

  def accept
    # find request instance
    @request = Request.find(params[:request_id])
    # acess accepted field in request
    @request.request_accepted = true
    @request.request_pending = false
    # change value to true, save
    if @request.save
      redirect_to requests_path
    else
      render '/my_hikes', status: :unprocessable_entity
    end
  end

  def reject
    @request = Request.find(params[:request_id])
    @request.request_accepted = false
    @request.request_pending = false
    if @request.save
      redirect_to requests_path
    else
      render '/my_hikes', status: :unprocessable_entity
    end
  end

  private

  def set_hike
    @hike = Hike.find(params[:hike_id])
  end

  def request_params
    params.require(:request).permit(:request_accepted, :request_pending)
  end
end

app/views/requests/index.html.erb
<% content_for :meta_title, "My Hikes" %>

<div class="page-container-flex">
    <h1 class="main-title">My Hikes</h1>

  <div class="hike-page-info-card">
    <h2>My Requests</h2>
    <% if current_user.received_requests.pending.empty? %>
      <p>You currently don't have any requests.</p>
    <% end %>
      <% @pending_requests.each do |request| %>
        <% if request.hike.user == current_user %>
        <div class="hike-request-card-flex">
          <div class="hikers-joined-details-flex">
          <% if !@pending_requests.nil? %>
            <%= link_to user_path(request.user), class: "request-user-info-flex" do %>

                <% if request.user.photo.attached? %>
                  <%= cl_image_tag request.user.photo.key, class: "avatar-large" %>
                <% end %>

                <p><%= request.user.first_name %> wants to join "<%= request.hike.hike_name.truncate(20, separator: ',')%>" </p>

            <% end %>

            <div class="request-accept-decline">
              <%= button_to 'Accept', request_accept_path(request), method: :post, class: "request-button-accept" %>
              <%= button_to 'Ignore', request_reject_path(request), method: :post, class: "request-button-reject" %>
            </div>

          <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <br>
      <div class="hr-line-flex">
      <hr>
      </div>
  </div>

<br>

  <div class="hike-page-info-card">
    <h2>My Upcoming Hikes ⛰️</h2>
          <% if current_user.upcoming_owned_hikes.empty?  && current_user.upcoming_joined_hikes.empty? %>
        <p> You currently don't have any upcoming Hikes. </p>
      <% else %>
    <div class="upcoming-hikes-flex-grid">
      <% current_user.upcoming_owned_hikes.each do |hike| %>
        <div class="upcoming-hike-and-info">
          <%= link_to hike_path(hike) do %>
            <% if hike.photo.attached? %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hike.photo.key, height: 160, crop: :fill %>')">
                <p class="your-hike">Your Hike</p>
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% else %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')">
                <p class="your-hike">Your Hike</p>
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%# </div> %>

      <%# <div class="upcoming-hikes-flex-grid"> %>
      <% current_user.upcoming_joined_hikes.each do |hike| %>
        <div class="upcoming-hike-and-info">
          <%= link_to hike_path(hike) do %>
            <% if hike.photo.attached? %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hike.photo.key, height: 160, crop: :fill %>')">
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% else %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')">
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <div class="hr-line-flex">
      <hr>
    </div>

    <div class="upcoming-hikes-flex-grid">
      <% current_user.upcoming_pending_hikes.each do |hike| %>
        <div class="upcoming-hike-and-info">
          <%= link_to hike_path(hike) do %>
            <% if hike.photo.attached? %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hike.photo.key, height: 160, crop: :fill %>')">
                <p class="your-hike">Pending</p>
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% else %>
              <div class="small-hike-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')">
                <p class="your-hike">Pending</p>
                <p class="small-hike-card-name"><%= hike.hike_name.truncate(20, separator: ',') %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
    <% if !current_user.upcoming_pending_hikes.empty? %>
    <br>
    <div class="hr-line-flex">
      <hr>
    </div>
    <% end %>

    <div class="backbuttonrequests">
      <div class="btn-yellow">
        <%= link_to "Find more Hikes", hikes_path, class: "logoutlink-profile"%>
      </div>
    </div>
  </div>
</div>